/*****************************************************************************
                Commands header file for Amnuts version 2.1.1
        Copyright (C) Andrew Collington - Last update: 25th May, 1999
 *****************************************************************************/


/* These are the general function names of the commands */
char *command_types[]={
  "General","Social","Messages","User","Ignores","Movement","Clones","Admin",
  #ifdef NETLINKS
    "Netlink",
  #endif
  "*"
  };


/* The enumerated type of above */
enum comtypes {
  CT_GENERAL,CT_SOCIAL,CT_MSG,CT_USER,CT_IGNORE,CT_MOVE,CT_CLONE,CT_ADMIN
  #ifdef NETLINKS
    ,CT_NETLINK
  #endif
  };


/* Although the commands are now set up like this, you still need to add the enum
   value in the correct place in the table below.  If you don't do this then the
   commands may not work correctly and it'll be YOUR OWN FAULT!!
  */
struct {
  char *name,*alias; int level,function;
  } command_table[]={
    { "quit",       "",    JAILED,  CT_GENERAL },
    { "look",       "",    NEW,     CT_GENERAL },
    { "mode",       "",    NEW,     CT_USER    },
    { "say",        "",    JAILED,  CT_SOCIAL  },
    { "shout",      "[",   SUPER,   CT_SOCIAL  },
    { "tell",       ">",   NEW,     CT_SOCIAL  },
    { "emote",      ":;",  NEW,     CT_SOCIAL  },
    { "semote",     "&!",  SUPER,   CT_SOCIAL  },
    { "pemote",     "</",  USER,    CT_SOCIAL  },
    { "echo",       "+",   USER,    CT_SOCIAL  },
    { "go",         "",    NEW,     CT_MOVE    },
    { "ignall",     "",    USER,    CT_IGNORE  },
    { "prompt",     "",    NEW,     CT_USER    },
    { "desc",       "",    NEW,     CT_USER    },
    { "inmsg",      "",    USER,    CT_USER    },
    { "outmsg",     "",    USER,    CT_USER    },
    { "public",     "",    USER,    CT_GENERAL },
    { "private",    "",    USER,    CT_GENERAL },
    { "knock",      "",    USER,    CT_GENERAL },
    { "invite",     "",    USER,    CT_GENERAL },
    { "topic",      "",    USER,    CT_SOCIAL  },
    { "move",       "",    WIZ,     CT_MOVE    },
    { "bcast",      "",    WIZ,     CT_SOCIAL  },
    { "who",        "@",   JAILED,  CT_GENERAL },
    { "people",     "",    WIZ,     CT_GENERAL },
    { "help",       "",    JAILED,  CT_GENERAL },
    { "shutdown" ,  "",    GOD,     CT_ADMIN   },
    { "news",       "",    USER,    CT_MSG     },
    { "read",       "",    NEW,     CT_MSG     },
    { "write",      "",    USER,    CT_MSG     },
    { "wipe",       "",    USER,    CT_MSG     },
    { "search",     "",    SUPER,   CT_GENERAL },
    { "review",     "",    USER,    CT_GENERAL },
  #ifdef NETLINKS
    { "home",       "",    USER,    CT_MOVE    },
  #endif
    { "ustat",      "",    USER,    CT_USER    },
    { "version",    "",    NEW,     CT_GENERAL },
    { "rmail",      "",    NEW,     CT_MSG     },
    { "smail",      "",    USER,    CT_MSG     },
    { "dmail",      "",    USER,    CT_MSG     },
    { "from",       "",    USER,    CT_MSG     },
    { "entpro",     "",    USER,    CT_USER    },
    { "examine",    "",    USER,    CT_USER    },
    { "rooms",      "",    USER,    CT_GENERAL },
  #ifdef NETLINKS
    { "rnet",       "",    USER,    CT_NETLINK },
    { "netstat",    "",    SUPER,   CT_NETLINK },
    { "netdata",    "",    ARCH,    CT_NETLINK },
    { "connect",    "",    GOD,     CT_NETLINK },
    { "disconnect", "",    GOD,     CT_NETLINK },
  #endif
    { "passwd",     "",    USER,    CT_USER    },
    { "kill",       "",    ARCH,    CT_ADMIN   },
    { "promote",    "",    WIZ,     CT_ADMIN   },
    { "demote",     "",    WIZ,     CT_ADMIN   },
    { "lban",       "",    WIZ,     CT_ADMIN   },
    { "ban",        "",    ARCH,    CT_ADMIN   },
    { "unban",      "",    ARCH,    CT_ADMIN   },
    { "vis",        "",    ARCH,    CT_USER    },
    { "invis",      "",    ARCH,    CT_USER    },
    { "site",       "",    WIZ,     CT_ADMIN   },
    { "wake",       "",    USER,    CT_SOCIAL  },
    { "twiz",       "",    WIZ,     CT_SOCIAL  },
    { "muzzle",     "",    WIZ,     CT_ADMIN   },
    { "unmuzzle",   "",    WIZ,     CT_ADMIN   },
    { "map",        "",    USER,    CT_GENERAL },
    { "logging",    "",    GOD,     CT_ADMIN   },
    { "minlogin",   "",    GOD,     CT_ADMIN   },
    { "system",     "",    SUPER,   CT_ADMIN   },
    { "charecho",   "",    NEW,     CT_USER    },
    { "clearline",  "",    ARCH,    CT_ADMIN   },
    { "fix",        "",    GOD,     CT_GENERAL },
    { "unfix",      "",    GOD,     CT_GENERAL },
    { "viewlog",    "",    WIZ,     CT_ADMIN   },
    { "accreq",     "",    NEW,     CT_USER    },
    { "cbuff",      "*",   USER,    CT_SOCIAL  },
    { "clone",      "",    ARCH,    CT_CLONE   },
    { "destroy",    "",    ARCH,    CT_CLONE   },
    { "myclones",   "",    ARCH,    CT_CLONE   },
    { "allclones",  "",    SUPER,   CT_CLONE   },
    { "switch",     "",    ARCH,    CT_CLONE   },
    { "csay",       "",    ARCH,    CT_CLONE   },
    { "chear",      "",    ARCH,    CT_CLONE   },
  #ifdef NETLINKS
    { "rstat",      "",    WIZ,     CT_NETLINK },
  #endif
    { "swban",      "",    ARCH,    CT_ADMIN   },
    { "afk",        "",    USER,    CT_USER    },
    { "cls",        "",    NEW,     CT_GENERAL },
    { "colour",     "",    NEW,     CT_GENERAL },
    { "ignshout",   "",    USER,    CT_IGNORE  },
    { "igntell",    "",    USER,    CT_IGNORE  },
    { "suicide",    "",    NEW,     CT_USER    },
    { "nuke",       "",    GOD,     CT_ADMIN   },
    { "reboot",     "",    GOD,     CT_ADMIN   },
    { "recount",    "",    GOD,     CT_MSG     },
    { "revtell",    "",    USER,    CT_SOCIAL  },
    { "purge",      "",    GOD,     CT_ADMIN   },
    { "history",    "",    WIZ,     CT_ADMIN   },
    { "expire",     "",    GOD,     CT_ADMIN   },
    { "bbcast",     "",    ARCH,    CT_SOCIAL  },
    { "show",       "'",   SUPER,   CT_SOCIAL  },
    { "ranks",      "",    NEW,     CT_GENERAL },
    { "wizlist",    "",    NEW,     CT_GENERAL },
    { "time",       "",    USER,    CT_GENERAL },
    { "ctopic",     "",    SUPER,   CT_SOCIAL  },
    { "copyto",     "",    USER,    CT_MSG     },
    { "nocopys",    "",    USER,    CT_MSG     },
    { "set",        "",    NEW,     CT_USER    },
    { "mutter",     "",    USER,    CT_SOCIAL  },
    { "makevis",    "",    ARCH,    CT_USER    },
    { "makeinvis",  "",    ARCH,    CT_USER    },
    { "sos",        "",    JAILED,  CT_SOCIAL  },
    { "ptell",      "",    USER,    CT_SOCIAL  },
    { "preview",    "",    USER,    CT_SOCIAL  },
    { "picture",    "",    SUPER,   CT_SOCIAL  },
    { "greet",      "",    SUPER,   CT_SOCIAL  },
    { "think",      "",    USER,    CT_SOCIAL  },
    { "sing",       "",    USER,    CT_SOCIAL  },
    { "ewiz",       "",    WIZ,     CT_SOCIAL  },
    { "suggest",    "",    USER,    CT_MSG     },
    { "rsug",       "",    WIZ,     CT_MSG     },
    { "dsug",       "",    GOD,     CT_MSG     },
    { "last",       "",    USER,    CT_USER    },
    { "macros",     "",    USER,    CT_USER    },
    { "rules",      "",    JAILED,  CT_GENERAL },
    { "uninvite",   "",    USER,    CT_GENERAL },
    { "lmail",      "",    ARCH,    CT_MSG     },
    { "arrest",     "",    WIZ,     CT_ADMIN   },
    { "unarrest",   "",    WIZ,     CT_ADMIN   },
    { "verify",     "",    NEW,     CT_MSG     },
    { "addhistory", "",    WIZ,     CT_ADMIN   },
    { "forwarding", "",    GOD,     CT_ADMIN   },
    { "revshout",   "",    USER,    CT_SOCIAL  },
    { "cshout",     "",    SUPER,   CT_SOCIAL  },
    { "ctells",     "",    USER,    CT_SOCIAL  },
    { "monitor",    "",    WIZ,     CT_ADMIN   },
    { "call",       ",",   USER,    CT_SOCIAL  },
    { "uncall",     "",    USER,    CT_SOCIAL  },
    { "ignlist",    "",    USER,    CT_IGNORE  },
    { "ignpics",    "",    USER,    CT_IGNORE  },
    { "ignwiz",     "",    WIZ,     CT_IGNORE  },
    { "igngreets",  "",    USER,    CT_IGNORE  },
    { "ignlogons",  "",    USER,    CT_IGNORE  },
    { "ignuser",    "",    USER,    CT_IGNORE  },
    { "create",     "",    WIZ,     CT_USER    },
    { "bfrom",      "",    USER,    CT_MSG     },
    { "samesite",   "",    WIZ,     CT_ADMIN   },
    { "save",       "",    ARCH,    CT_ADMIN   },
    { "shackle",    "",    ARCH,    CT_ADMIN   },
    { "unshackle",  "",    ARCH,    CT_ADMIN   },
    { "join",       "",    SUPER,   CT_MOVE    },
    { "cemote",     "",    ARCH,    CT_CLONE   },
    { "revafk",     "",    USER,    CT_SOCIAL  },
    { "cafk",       "",    USER,    CT_SOCIAL  },
    { "revedit",    "",    USER,    CT_SOCIAL  },
    { "cedit",      "",    USER,    CT_SOCIAL  },
    { "listen",     "",    USER,    CT_IGNORE  },
    { "hangman",    "",    USER,    CT_GENERAL },
    { "guess",      "",    USER,    CT_GENERAL },
    { "retire",     "",    GOD,     CT_ADMIN   },
    { "unretire",   "",    GOD,     CT_ADMIN   },
    { "memcount",   "",    GOD,     CT_ADMIN   },
    { "cmdcount",   "",    ARCH,    CT_ADMIN   },
    { "rcountu",    "",    GOD,     CT_ADMIN   },
    { "recaps",     "",    GOD,     CT_ADMIN   },
    { "setcmdlev",  "",    ARCH,    CT_ADMIN   },
    { "grepu",      "",    WIZ,     CT_GENERAL },
    { "shoot",      "",    USER,    CT_GENERAL },
    { "reload",     "",    USER,    CT_GENERAL },
    { "xcom",       "",    ARCH,    CT_ADMIN   },
    { "gcom",       "",    ARCH,    CT_ADMIN   },
    { "sfrom",      "",    WIZ,     CT_MSG     },
    { "rloadrm",    "",    GOD,     CT_ADMIN   },
    { "autopromo",  "",    GOD,     CT_ADMIN   },
    { "sayto",      "-",   USER,    CT_SOCIAL  },
    { "friends",    "",    USER,    CT_SOCIAL  },
    { "fsay",       "",    USER,    CT_SOCIAL  },
    { "femote",     "",    USER,    CT_SOCIAL  },
    { "bring",      "",    SUPER,   CT_MOVE    },
    { "force",      "",    GOD,     CT_ADMIN   },
    { "calendar",   "",    USER,    CT_GENERAL },
    { "fwho",       "",    USER,    CT_GENERAL },
    { "myroom",     "",    SUPER,   CT_MOVE    },
    { "mylock",     "",    SUPER,   CT_GENERAL },
    { "visit",      "",    USER,    CT_MOVE    },
    { "mypaint",    "",    SUPER,   CT_GENERAL },
    { "ignbeeps",   "",    USER,    CT_IGNORE  },
    { "beep",       "",    SUPER,   CT_SOCIAL  },
    { "rmadmin",    "",    ARCH,    CT_ADMIN   },
    { "mykey",      "",    SUPER,   CT_GENERAL },
    { "mybgone",    "",    SUPER,   CT_GENERAL },
    { "*","*",-1,-1 } /* stopping clause - do not remove */
  };


/* Values of commands, used in switch in exec_com() */
enum comvals {
  QUIT,
  LOOK,
  MODE,
  SAY,
  SHOUT,
  TELL,
  EMOTE,
  SEMOTE,
  PEMOTE,
  ECHO,
  GO,
  IGNALL,
  PROMPT,
  DESC,
  INPHRASE,
  OUTPHRASE,
  PUBCOM,
  PRIVCOM,
  LETMEIN,
  INVITE,
  TOPIC,
  MOVE,
  BCAST,
  WHO,
  PEOPLE,
  HELP,
  SHUTDOWN,
  NEWS,
  READ,
  WRITE,
  WIPE,
  SEARCH,
  REVIEW,
#ifdef NETLINKS
  HOME,
#endif
  STATUS,
  VER,
  RMAIL,
  SMAIL,
  DMAIL,
  FROM,
  ENTPRO,
  EXAMINE,
  RMST,
#ifdef NETLINKS
  RMSN,     NETSTAT,    NETDATA,    CONN,     DISCONN,
#endif
  PASSWD,
  KILL,
  PROMOTE,
  DEMOTE,
  LISTBANS,
  BAN,
  UNBAN,
  VIS,
  INVIS,
  SITE,
  WAKE,
  WIZSHOUT,
  MUZZLE,
  UNMUZZLE,
  MAP,
  LOGGING,
  MINLOGIN,
  SYSTEM,
  CHARECHO,
  CLEARLINE,
  FIX,
  UNFIX,
  VIEWLOG,
  ACCREQ,
  REVCLR,
  CREATE,
  DESTROY,
  MYCLONES,
  ALLCLONES,
  SWITCH,
  CSAY,
  CHEAR,
#ifdef NETLINKS
  RSTAT,
#endif
  SWBAN,
  AFK,
  CLS,
  COLOUR,
  IGNSHOUTS,
  IGNTELLS,
  SUICIDE,
  DELETE,
  REBOOT,
  RECOUNT,
  REVTELL,
  PURGE,
  HISTORY,
  EXPIRE,
  BBCAST,
  SHOW,
  RANKS,
  WIZLIST,
  TIME,
  CTOPIC,
  COPYTO,
  NOCOPIES,
  SET,
  MUTTER,
  MKVIS,
  MKINVIS,
  SOS,
  PTELL,
  PREVIEW,
  PICTURE,
  GREET,
  THINK,
  SING,
  WIZEMOTE,
  SUG,
  RSUG,
  DSUG,
  LAST,
  MACROS,
  RULES,
  UNINVITE,
  LMAIL,
  ARREST,
  UNARREST,
  VERIFY,
  ADDHISTORY,
  FORWARDING,
  REVSHOUT,
  CSHOUT,
  CTELLS,
  MONITOR,
  QCALL,
  UNQCALL,
  IGNLIST,
  IGNPICS,
  IGNWIZ,
  IGNGREETS,
  IGNLOGONS,
  IGNUSER,
  ACCOUNT,
  BFROM,
  SAMESITE,
  SAVEALL,
  SHACKLE,
  UNSHACKLE,
  JOIN,
  CEMOTE,
  REVAFK,
  CAFK,
  REVEDIT,
  CEDIT,
  LISTEN,
  HANGMAN,
  GUESS,
  RETIRE,
  UNRETIRE,
  MEMCOUNT,
  CMDCOUNT,
  RCOUNTU,
  RECAPS,
  SETCMDLEV,
  GREPUSER,
  SHOOT,
  RELOAD,
  XCOM,
  GCOM,
  SFROM,
  RLOADRM,
  SETAUTOPROMO,
  SAYTO,
  FRIENDS,
  FSAY,
  FEMOTE,
  BRING,
  FORCE,
  CALENDAR,
  FWHO,
  MYROOM,
  MYLOCK,
  VISIT,
  MYPAINT,
  IGNBEEPS,
  BEEP,
  RMADMIN,
  MYKEY,
  MYBGONE
} com_num;



/* Subsection of the 'set' command - for setting of attributes */
struct {
  char *type;
  char *desc;
  } setstr[]={
    {"show","show the current attributes setting"},
    {"gender","sets your gender (male, female, or neuter)"},
    {"age","set your age for people to see"},
    {"email","enter your email address"},
    {"homepage","enter your homepage address"},
    {"hide","makes your email visible to only you and the law, or everyone (toggle)"},
    {"wrap","sets screen wrap to be on or off (toggle)"},
    {"pager","sets how many lines per page of the pager you get"},
    {"colour","display in colour or not (toggle)"},
    {"room","lets you log back into the room you left from, if public (toggle)"},
    {"autofwd","lets you receive smails via your email address."},
    {"password","lets you see your password when entering it at the login (toggle)"},
    {"rdesc","lets you ignore room descriptions (toggle)"},
    {"command","Displays the command lisiting differently (toggle)"},
    {"recap","Allows you to have caps in your name"},
    {"icq","Allows you to put in your ICQ number"},
    {"alert","lets you know when someone in your friends list logs on (toggle)"}, 
    {"*",""}
  };
enum setval {
  SETSHOW,        SETGEND,    SETAGE,     SETEMAIL,       SETHOMEP,
  SETHIDEEMAIL,   SETWRAP,    SETPAGER,   SETCOLOUR,      SETROOM,
  SETFWD,         SETPASSWD,  SETRDESC,   SETCOMMAND,     SETRECAP,
  SETICQ,         SETALERT
  } set_val;
