version       0.3
password      NUKyNCCLvgLH.
promote_date  on Friday 3rd September 1999 at 09:37pm
times         938967204 37106 704 938199212
levels        6 6 0 0
general       -1 0 0 0 1 0 1 27
user_set      0 0 0 23 1 1 0 1 0 0 1 0 #UNSET
user_ignores  0 0 0 0 0 0 0 0
fighting      0 0 0 0 6 10
purging       1 942423204
last_site     localhost reception
mail_verify   #EMAILSET
description   should be nuked asap
in_phrase     enters
out_phrase    goes
email         andyc@localhost.localnet
homepage      #UNSET
recap_name    ~OL~FTt~FRE~FGs~FYT
